include hyde.conf
# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Performance (laptop - reduce GPU/iGPU usage)
repaint_delay               16
input_delay                 5
sync_to_monitor             yes
cursor_blink_interval       0
scrollback_lines            2000
