#aquí van todos los programas que queremos que se abran apenas se inicia hyperland
#─────────────────────────────────────────────

#---NECESITAN SUDO----

#asegurarse de que se activa tlp
exec-once=sudo systemctl enable --now tlp && sudo tlp start


#---NO SUDO----

#timers de la pantalla
exec-once = hypridle

#poner fondo de pantalla
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh
#activar portapapeles
exec-once = wl-paste --watch cliphist store


#waybar
exec-once = waybar && ~/.config/waybar/scripts/autohide.sh
