general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

#apagar pantalla y liberar ram no usada (tiene sudo)
listener {
    timeout = 600          # 10 min — apagar pantalla
    on-timeout = hyprctl dispatch dpms off && sync && echo 3 | sudo tee /proc>
    on-resume = hyprctl dispatch dpms on
}
#suspender pc
listener {
    timeout =  660         # 11 min — suspender
    on-timeout = systemctl suspend
}
